config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:sessions], controllers: {sessions: "sessions", passwords: "passwords"}

  as :user do
    get "signin", to: "devise/sessions#new", as: :new_user_session
    post "signin", to: "devise/sessions#create", as: :user_session
    delete "signout", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  get "pages/index"

  get "/profile" => "pages#profile"
  get "/profile/:id" => "pages#profile_show"

  get "/about" => "pages#about"
  get "/terms-of-service" => "pages#tos", as: :tos
  get "/privacy-policy" => "pages#privacy", as: :privacy

  resources :spots do
    resources :media, only: [:new, :create]
  end

  resources :media, only: [:destroy]

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  before_destroy :delete_from_s3

  private

  def delete_from_s3
    S3_BUCKET.delete_objects({
      delete: {
        objects: [
          {key: self.s3_bucket_object_key}
        ]
      }  
    })
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :media, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  # before_action :set_s3_direct_post, only: [:new]

  def new
    @medium = Medium.new
    @spot = Spot.find(params[:spot_id])
    set_s3_direct_post
  end

  def create
    @spot = Spot.find(params[:spot_id])
    medium = current_user.media.build(
      s3_path: params[:file],
      spot: @spot,
      s3_bucket_object_key: params[:key]
    )
    medium.save
    flash[:notice] = "Media added successfully!"
    redirect_to spot_path(@spot)
  end

  def destroy
    medium_id = params[:id]
    medium = Medium.find(medium_id);
    medium.destroy
    flash.now[:notice] = "Media deleted successfully."
    render json: {
      status: 200,
      flash_html: view_context.flash_messages,
      medium_id: medium_id
    }
  end

  private
  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{@spot.id}/#{SecureRandom.uuid}-${filename}", success_action_status: '201', acl: 'public-read')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @featured_spots = Spot.limit(3)
  end

  def profile
    if !user_signed_in?
      redirect_to new_user_session_path
    end
    @media = Medium.where(user: current_user)
  end

  def profile_show
    @user = User.find(params[:id])
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController

  def after_resetting_password_path_for(resource)
    root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new
    self.resource = resource_class.new(sign_in_params)
    store_location_for(resource, params[:redirect_to])
    super
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    @spots = Spot.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@spots) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
      marker.infowindow render_to_string( :template => "spots/infobox", locals: {:spot => spot}, layout: false)
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @hash = Gmaps4rails.build_markers(@spot) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
    end

    @media = Medium.where(spot: @spot)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_class
    controller.class.to_s.gsub("Controller", '').underscore.gsub("/", '_') + " " + content_for(:page_class)
  end

  def flash_messages
    flash.map do |key, msg|
      content_tag :div, (msg + "<div class='right'>#{icon 'close', class: 'pointer', data: {dismiss: "flash"}}</div>").html_safe, :id => key, :class => "#{key} flash p2 bold #{'abs' if current_page? root_path}"
    end.join.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spot_images_helper.rb
module SpotImagesHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: "viewport", content: "width=device-width"}
    %title IcySpots
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Barrio"
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans"

    = render 'shared/navbar'
    = flash_messages

    = yield
    
    = render 'shared/footer'
    = javascript_include_tag "https://maps.google.com/maps/api/js?key=#{ENV['GOOGLE_API_BROWSER_KEY']}"
    = javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js"
    = javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js"
    = javascript_include_tag 'application'
    
    = yield(:after_js)

app/views/media/create.html.haml
%h1 SpotImages#create
%p Find me in app/views/spot_images/create.html.erb

app/views/media/new.html.haml
.max-width-4.mx-auto.p2
  %h1.barrio 
    Add media for 
    %span.orange= @spot.name
  %h2.barrio Rules
  %ul
    %li Uploaded media must be for this spot
    %li The following media types are allowed: JPG/JPEG, PNG, GIF

  = simple_form_for [@spot, @medium], html: {class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host }} do |f|
    = file_field_tag "file"
    = f.submit "Add media", class: "btn btn-primary"

= content_for(:after_js) do

  :javascript
    /* TODO ensure that files submitted conform to image magic number specifications

    function submitForm() {
       // var fileList = new Array();
       // fileList = document.getElementById("image").files;
       var file = document.getElementById("file").files;
      
       var fr = new FileReader();
       if (FileReader && file) {
          fr.readAsArrayBuffer(file[0]);
          fr.onload = function () {
             window.imageData = fr.result;
             console.log(imageData);
          };
       }
    }

    */

    $(document).ready(function() {
      $submit = $('input[type=submit]');

      $submit.on('click', function(e){
        e.preventDefault();

        if($("input:file").val() == ""){
          alert('Please choose a file!');
        }
        else {
          $('form').submit();
        }
      });



      $(function() {
        $('.directUpload').find("input:file").each(function(i, elem) {

          var fileInput    = $(elem);
          var form         = $(fileInput.parents('form:first'));
          var submitButton = form.find('input[type="submit"]');
          var progressBar  = $("<div class='bar p1'></div>");
          var barContainer = $("<div class='progress'></div>").append(progressBar);

          fileInput.after(barContainer);

          fileInput.fileupload({
            add: function(e, data) {
              var uploadErrors = [];
              var acceptFileTypes = /^image\/(gif|jpe?g|png)$/i;
              if(data.originalFiles[0]['type'].length && !acceptFileTypes.test(data.originalFiles[0]['type'])) {
                  uploadErrors.push('Not an accepted file type');
              }
              if(data.originalFiles[0]['size'].length && data.originalFiles[0]['size'] > 5000000) {
                  uploadErrors.push('Filesize is too big');
              }
              if(uploadErrors.length > 0) {
                  alert(uploadErrors.join("\n"));
                  fileInput.val("");
              } else {
                  data.submit();
              }
            },
            fileInput:       fileInput,
            url:             form.data('url'),
            type:            'POST',
            autoUpload:       true,
            formData:         form.data('form-data'),
            paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
            dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
            replaceFileInput: false,
            progressall: function (e, data) {
              var progress = parseInt(data.loaded / data.total * 100, 10);
              progressBar.css('width', progress + '%')
            },
            start: function (e) {
              submitButton.prop('disabled', true);

              progressBar.
                css('display', 'block').
                css('width', '0%').
                text("Loading...");
            },
            done: function(e, data) {
              submitButton.prop('disabled', false);
              progressBar.text("Uploading done");

              // extract key and generate URL from response
              var key   = $(data.jqXHR.responseXML).find("Key").text();
              var url   = '//' + form.data('host') + '/' + key;
          
              // create hidden fields
              var input = $("<input />", { type:'hidden', name: fileInput.attr('name'), value: url })
              form.append(input);

              var input = $("<input />", { type:'hidden', name: 'key', value: key })
              form.append(input);
            },
            fail: function(e, data) {
              submitButton.prop('disabled', false);
              progressBar.css("background", "red").text("Failed");
            }
          });
        });
      });
    });

app/views/pages/about.html.haml
.container
  %h1 About

  %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed est metus, imperdiet sed tristique eu, gravida a dolor. Nullam blandit mauris non sodales porta. Nunc ullamcorper luctus diam, maximus rhoncus nisi fringilla ac. Proin laoreet aliquet lorem eu volutpat. Nam ac mi mi. Fusce sit amet tortor id elit dignissim finibus eu sit amet metus. Aliquam in ullamcorper neque, ut egestas orci. Donec augue risus, dignissim fermentum pretium at, ullamcorper sit amet ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum feugiat tortor ac nunc efficitur maximus. Phasellus posuere quam a fermentum tincidunt.

app/views/pages/index.html.haml
.parallax-window.flex.flex-column.items-center.justify-center{style: "height: 100%"}
  %div{style: "margin-top: -20%;"}
    .h1.orange.barrio{style: "font-size: 4em;"} IcySpots
    .h2.barrio.yellow{style: "font-size: 3em;"} Repository of skatespots worldwide
.bg-white.center{style: "min-height: 50%"}
  .max-width-4.mx-auto
    %h1.mt4.mb2.orange.barrio Featured Spots
    .clearfix.p4
      - @featured_spots.each do |spot|
        = link_to spot_path(spot), class: "pointer" do
          .col.col-12.sm-col.sm-col-4.p2
            .h2.my2.barrio.black= spot.name
            = image_tag "info_box_images/#{spot.infobox_image}"


.bg-orange{style: "height: 100%;"}
  .h1.orange SpotRepo

-content_for :after_js do
  :javascript
    jQuery('.parallax-window').parallax({imageSrc: "#{image_path "sb-wallpaper-orange-overlay-40.jpg"}"});

app/views/pages/profile.html.haml
.max-width-4.mx-auto
  .clearfix
    .col.col-12
      .py2
        %h1 Profile
        %h2= current_user.email
    .col.col-12
      %h1 My footy
      .clearfix
        - @media.each do |medium|
          .col.col-3{id: medium.id}
            = image_tag "http://#{medium.s3_path}", class: 'fit', style: 'max-height: 150px;'
            = link_to medium_path(medium), remote: true, method: :delete, data: {confirm: "Are you sure?"} do
              = icon('trash', class: 'black')


= content_for(:after_js) do
  :javascript
    $(document).ready(function(){
      $(document).on('ajax:success', function(e, data, status, xhr){
        $('#' + data.medium_id).remove();
        $('.topnav').after(data.flash_html);
        $('[data-dismiss=flash]').on('click', function(){
          $(this).parents('.flash').slideUp();
        });
      }).on('ajax:error',function(e, xhr, status, error){
        // Error happened
      });
    });
  

app/views/shared/_footer.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.fixed-bottom
  %a.navbar-brand.barrio.orange{:href => "/"} ICYSPOTS
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.ml-auto
      %li.nav-item
        = link_to "Terms of Service", tos_path, class: "nav-link barrio"
      %li.nav-item
        = link_to "Privacy Policy", privacy_path, class: "nav-link barrio"

app/views/shared/_navbar.html.haml
%ul{class:"topnav", id:"myTopnav"}
  %li
    = link_to "IcySpots", root_path, class: "orange barrio"
  %li
    = link_to "Spot Map", spots_path, class: "white barrio"

  .right
    - if user_signed_in?
      %li
        = link_to "Profile", profile_path, class: "white barrio"
      %li
        = link_to "Sign out", destroy_user_session_path, method: :delete, class: 'white barrio'
    - else
      %li
        = link_to "Sign in", new_user_session_path, class: 'white barrio'

app/views/spots/index.html.haml
.spots.index
  #map

- content_for(:after_js) do
  :javascript
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(#{raw @hash.to_json});
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();

        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });

app/views/spots/infobox.html.haml
.infobox.center
  %h4
    = link_to spot.name, spot_path(spot), class: 'text-decoration-none orange'
  = image_tag("info_box_images/#{spot.infobox_image}")
  %p
    %i= spot.address

app/views/spots/show.html.haml
.max-width-4.mx-auto
  .clearfix
    .col.col-12.sm-col.sm-col-6.p2
      %h1.spot-name.orange.barrio= @spot.name
      %h2= @spot.address
      %p= @spot.description
    .col.col-12.sm-col.sm-col-6.p2
      #map{style: "width: 100%; height: 512px;"}
    .col.col-12
      %h1.barrio.orange Featured media
      - if user_signed_in?
        = link_to 'Upload media', new_spot_medium_path(@spot.id), class: 'orange text-decoration-none'
      - else
        = link_to "Sign in to add media", new_user_session_path(redirect_to: new_spot_medium_path(@spot)); 
      .clearfix 
        - @media.each do |medium|
          .col.col-3.p2
            .featured-medium-card{style: 'box-shadow: 10px 10px 5px #888888;'}
              .featured-medium-img-wrapper.center{style: 'height:150px; overflow:hidden; object-fit: cover;border: 1px solid orange;'}
                = link_to "http://#{medium.s3_path}",  data: {lightbox: "image-1", title:"My caption"} do
                  = image_tag "http://#{medium.s3_path}", style: 'max-height: 150px;'
              .featured-medium-footer.pr2{style: 'background-color:black;color:white;border-left:1px solid red;border-bottom: 1px solid red;border-right: 1px solid red;'}
                = link_to "#{medium.user.email}", "/profile/#{medium.user.id}"


= content_for(:after_js) do
  :javascript
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(#{raw @hash.to_json});
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });